__author__ = 'Akuukis <akuukis@kalvis.lv'

import datetime
import re
import math

from beancount.core.amount import Amount, add, sub, mul, div
from beancount.core import data
from beancount.core.position import Position
from beancount.core.number import ZERO, D, round_to

from .common_functions import check_aliases_entry
from .common_functions import check_aliases_posting
from .common_functions import distribute_over_duration
from .common_functions import get_dates
from .common_functions import longest_leg

__plugins__ = ['spread']


def get_entries(entry, selected_postings, params, MIN_VALUE, MAX_NEW_TX):
    all_amounts = []
    all_closing_dates = []
    for _, _, params, posting in selected_postings:
        total_duration, closing_dates = get_dates(params, entry.date, MAX_NEW_TX)
        all_closing_dates.append(closing_dates)
        all_amounts.append( distribute_over_duration(total_duration, posting.units.number, MIN_VALUE) )

    map_closing_dates = {}
    for closing_dates in all_closing_dates:
        for date in closing_dates:
            map_closing_dates[date] = True

    merged_closing_dates = list(map_closing_dates.keys())
    merged_closing_dates.sort()

    new_transactions = []
    for i in range(len(merged_closing_dates)):
        postings = []

        for p, new_account, _, posting in selected_postings:
            if i < len(all_amounts[p]):
                amount = Amount(all_amounts[p][i], posting.units.currency)
                # Income/Expense to be spread
                postings.append(data.Posting(account=posting.account,
                                  units=amount,
                                  cost=None,
                                  price=None,
                                  flag=posting.flag,
                                  meta=None))

                # Asset/Liability that buffers the difference
                postings.append(data.Posting(account=new_account,
                                  units=mul(amount, D(-1)),
                                  cost=None,
                                  price=None,
                                  flag=posting.flag,
                                  meta=None))

        if len(postings) > 0:
            e = data.Transaction(
                date=closing_dates[i],
                meta=entry.meta,
                flag=entry.flag,
                payee=entry.payee,
                narration=entry.narration + ' (Generated by interpolate-spread %d/%d)'%(i+1, total_duration), # TODO: SUFFIX
                tags={'spread'}, # TODO: TAG
                links=entry.links,
                postings=postings)
            new_transactions.append(e)

    return new_transactions


def spread(entries, options_map, config_string):
    """Add depreciation entries for fixed assets.  See module docstring for more
    details and example"""
    errors = []

    ## Parse config and set defaults
    config_obj = eval(config_string, {}, {})
    if not isinstance(config_obj, dict):
        raise RuntimeError("Invalid plugin configuration: should be a single dict.")
    ACCOUNT_INCOME   = config_obj.pop('account_income'  , 'Liabilities:Current')
    ACCOUNT_EXPENSES = config_obj.pop('account_expenses', 'Assets:Current')
    ALIASES_BEFORE   = config_obj.pop('aliases_before'  , ['spreadBefore'])
    ALIASES_AFTER    = config_obj.pop('aliases_after'   , ['spreadAfter', 'spread'])
    ALIAS_SEPERATOR  = config_obj.pop('aliases_after'   , '-')
    DEFAULT_PERIOD   = config_obj.pop('default_period'  , 'Month')
    DEFAULT_METHOD   = config_obj.pop('default_method'  , 'SL')
    MIN_VALUE        = config_obj.pop('min_value'       , 0.05)
    MAX_NEW_TX       = config_obj.pop('max_new_tx'      , 9999)
    SUFFIX           = config_obj.pop('suffix'          , ' (Generated by interpolate-spread)')
    TAG              = config_obj.pop('tag'             , 'spread')
    MIN_VALUE = D(str(MIN_VALUE))
    TRANSLATION = {
        'Income': ACCOUNT_INCOME,
        'Expenses': ACCOUNT_EXPENSES
    }

    ## Filter transaction entries that have tag or meta or its posting has meta.
    newEntries = []
    for i, entry in enumerate(entries):

        if not hasattr(entry, 'postings'):
            continue

        selected_postings = []
        for i, posting in enumerate(entry.postings):
            # TODO: ALIASES_BEFORE
            params = check_aliases_posting(ALIASES_AFTER, posting) \
                  or check_aliases_entry(ALIASES_AFTER, entry, ALIAS_SEPERATOR) \
                  or False
            if not params:
                continue
            account = posting.account.split(':')
            if not account[0] in TRANSLATION:
                continue
            new_account = TRANSLATION[account[0]]+':'+':'.join(account[1:])
            selected_postings.append( (i, new_account, params, posting) )

        for i, new_account, params, posting in selected_postings:
            entry.postings.pop(i)
            entry.postings.insert(i, data.Posting(
                account=new_account,
                units=Amount(posting.units.number, posting.units.currency),
                cost=None,
                price=None,
                flag=None,
                meta=None))

        if len(selected_postings) > 0:
            newEntries = newEntries + get_entries(entry, selected_postings, params, MIN_VALUE, MAX_NEW_TX)

    return entries + newEntries, errors
